### Post Single user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "yo2",
  "name": "yo2",
  "password": "pw2"
}
### Get all users
GET http://localhost:3003/api/users
Content-Type: application/json
